### ISSUE TITLE
BPM cannot build projects with external handlebars templates

### ISSUE THREAD

**Issue by LuisSala** [bpm/bpm#27]
BPM crashes when I have handlebars templates contained in a separate directory. 

My package.json contains:

  "bpm:build": {
    "bpm_libs.js": {
      "directories": [
        "lib",
    "templates"
      ],
      "minifier": "uglify-js"
    }

See: https://github.com/LuisSala/bpm_handlebars_bug

**Comment by wagenet** [comment]
There are a couple issues here. First off, you never require sproutcore in your app. You should have spade.require('sproutcore') at the top of your main.js. This is causing the minifier failures.
Secondly, the exact behavior of handlebars formats is currently being debated. If you'd like to chime in, this is the place to do so: https://github.com/bpm/bpm/issues/28
Since I think that covers your issues I'm closing this ticket.

**Comment by LuisSala** [comment]
Thanks!
